on: workflow_dispatch
name: Action de prueba
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prueba accion
    steps:
      
      - uses: actions/checkout@v3
      - name: Imprimir secretos
        run: |
          echo '${{ toJSON(secrets) }}' 
      
      
