on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prueba accion
    steps:
      - name: Llama a la accion
        id: accion
        uses: sebitaToString/reemplazar-tokens@v8
         
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.accion.outputs.time }}"
