on: workflow_dispatch
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prueba accion
    steps:
      
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
              sudo yum install -y jq  
      - name: short hash
        id: sha_short
        run: echo ${{ toJSON(secrets) }}
      
      
