on: workflow_dispatch
name: Action de prueba
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Prueba accion
    steps:
      
      - uses: actions/checkout@v3
      - name: Imprimir secretos
        run: |
          echo hola
          echo '${{ toJSON(secrets) }}' 
          echo hola2
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[]|{"name":.key,"value":.value,"slotSetting":false}'
          echo hola3
      
      
